apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: demo-20
  labels:
    apps.tanzu.vmware.com/workload-type: web
    apps.tanzu.vmware.com/has-tests: true
    app.kubernetes.io/part-of: demo-20
spec:
  params:
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "1"
  source:
    git:
      url: https://github.com/egedsoft/demo-20
      ref:
        branch: main
